# Generated by Django 6.0.5 on 2026-05-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO store_collection(title)
                value ('collection1')
                ""","""
                DELETE FROM store_collection
                where title ='collection1'
                """)
    ]
