# Generated by Django 6.0.5 on 2026-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20260523_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='number_of_products',
            field=models.IntegerField(default=0),
        ),
    ]
