# Generated by Django 6.0.5 on 2026-05-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_number_of_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
